### ISSUE TITLE
CronJob for etcd defrag

### ISSUE THREAD

**Issue by mkjpryor** [stackhpc/capi-helm-charts#43]
We should add a `CronJob` to defragment the etcd database.

https://etcd.io/docs/v3.5/op-guide/maintenance/#defragmentation
https://www.ibm.com/docs/en/cloud-private/3.2.x?topic=administration-managing-etcd-clusters

**Comment by bbezak** [comment]
addressed with https://github.com/stackhpc/capi-helm-charts/pull/228
